tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "inverse-primary": "#4ae183",
                "surface-container-highest": "#dce5da",
                "outline-variant": "#bbcbbb",
                "error": "#ba1a1a",
                "on-secondary-container": "#00705c",
                "tertiary-fixed-dim": "#ffb59d",
                "outline": "#6c7b6d",
                "on-surface": "#161d17",
                "on-tertiary": "#ffffff",
                "secondary-fixed-dim": "#4eddbb",
                "on-secondary-fixed-variant": "#005141",
                "background": "#f3fcf1",
                "on-error-container": "#93000a",
                "surface-container-low": "#eef6eb",
                "surface-dim": "#d4dcd2",
                "tertiary": "#98472a",
                "inverse-surface": "#2b322b",
                "primary-fixed": "#6bfe9c",
                "primary-container": "#2ecc71",
                "on-tertiary-fixed-variant": "#793015",
                "surface-container-lowest": "#ffffff",
                "surface-variant": "#dce5da",
                "on-error": "#ffffff",
                "secondary-container": "#6cf7d4",
                "primary-fixed-dim": "#4ae183",
                "surface-container-high": "#e2ebe0",
                "on-surface-variant": "#3d4a3e",
                "inverse-on-surface": "#ebf3e8",
                "on-primary-container": "#005027",
                "tertiary-fixed": "#ffdbd0",
                "on-primary": "#ffffff",
                "on-secondary-fixed": "#002019",
                "secondary-fixed": "#6ff9d6",
                "surface-bright": "#f3fcf1",
                "error-container": "#ffdad6",
                "tertiary-container": "#ff9875",
                "on-background": "#161d17",
                "surface": "#f3fcf1",
                "on-tertiary-container": "#772e14",
                "surface-container": "#e8f0e5",
                "on-primary-fixed": "#00210c",
                "on-secondary": "#ffffff",
                "on-tertiary-fixed": "#390c00",
                "primary": "#006d37",
                "surface-tint": "#006d37",
                "secondary": "#006b58",
                "on-primary-fixed-variant": "#005228"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-mobile": "20px",
                "gutter": "16px",
                "md": "16px",
                "xs": "4px",
                "xl": "40px",
                "container-max": "1200px",
                "base": "4px",
                "lg": "24px",
                "sm": "8px"
            },
            "fontFamily": {
                "body-md": ["Inter"],
                "body-sm": ["Inter"],
                "display-lg": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "body-lg": ["Inter"],
                "headline-lg": ["Plus Jakarta Sans"],
                "label-lg": ["Inter"],
                "label-sm": ["Inter"]
            },
            "fontSize": {
                "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "display-lg": ["36px", {"lineHeight": "1.2", "fontWeight": "700"}],
                "headline-md": ["22px", {"lineHeight": "1.4", "fontWeight": "600"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-lg": ["28px", {"lineHeight": "1.3", "fontWeight": "700"}],
                "label-lg": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "600"}],
                "label-sm": ["12px", {"lineHeight": "1.2", "fontWeight": "500"}]
            }
        },
    },
};
